using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using Astra.Core.Reporting;

namespace Astra.Services.Reporting
{
    /// <summary>
    /// 将 <see cref="TestReportData"/> 渲染为自包含的 HTML 报告（图表以 base64 PNG 内嵌）。
    /// </summary>
    public static class ReportHtmlBuilder
    {
        public static string Build(TestReportData data)
        {
            var sb = new StringBuilder(32_768);
            sb.AppendLine("<!DOCTYPE html><html lang='zh-CN'><head><meta charset='utf-8'/>");
            sb.AppendLine($"<title>测试报告 - {E(data.SN)}</title>");
            AppendStyles(sb);
            sb.AppendLine("</head><body>");

            AppendHeader(sb, data);
            AppendOverallResult(sb, data);

            if (data.ScalarJudgments.Count > 0)
                AppendScalarJudgmentTable(sb, data.ScalarJudgments);

            if (data.CurveJudgments.Count > 0)
                AppendCurveJudgmentTable(sb, data.CurveJudgments);

            if (data.Charts.Any(c => !string.IsNullOrEmpty(c.ImageBase64)))
                AppendChartGallery(sb, data.Charts);

            if (data.NodeSummaries.Count > 0)
                AppendNodeSummaryTable(sb, data.NodeSummaries);

            if (data.TextArtifacts.Count > 0)
                AppendTextArtifacts(sb, data.TextArtifacts);

            sb.AppendLine("<footer style='margin-top:40px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:11px;color:#94a3b8;'>");
            sb.AppendLine($"Generated by Astra Test Report Engine &mdash; {data.EndTime:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("</footer></body></html>");
            return sb.ToString();
        }

        private static void AppendStyles(StringBuilder sb)
        {
            sb.AppendLine(@"<style>
:root{--ok:#22c55e;--ng:#ef4444;--border:#e5e7eb;--bg-header:#f8fafc;}
*{box-sizing:border-box;}
body{font-family:'Segoe UI','Microsoft YaHei',sans-serif;margin:0;padding:24px 32px;color:#1e293b;background:#fff;}
h1{font-size:24px;border-bottom:2px solid #3b82f6;padding-bottom:8px;}
h2{font-size:18px;color:#334155;margin-top:32px;border-left:4px solid #3b82f6;padding-left:12px;}
table{border-collapse:collapse;width:100%;margin:12px 0;}
th,td{border:1px solid var(--border);padding:8px 12px;text-align:left;font-size:13px;}
th{background:var(--bg-header);font-weight:600;}
.pass{color:var(--ok);font-weight:700;} .fail{color:var(--ng);font-weight:700;}
.badge-ok{background:var(--ok);color:#fff;padding:4px 16px;border-radius:4px;font-size:20px;font-weight:700;display:inline-block;}
.badge-ng{background:var(--ng);color:#fff;padding:4px 16px;border-radius:4px;font-size:20px;font-weight:700;display:inline-block;}
.chart-card{display:inline-block;margin:8px;border:1px solid var(--border);border-radius:8px;overflow:hidden;vertical-align:top;}
.chart-card img{display:block;max-width:100%;}
.chart-title{padding:8px 12px;font-size:13px;font-weight:600;background:var(--bg-header);}
.chart-desc{padding:4px 12px 8px;font-size:12px;color:#64748b;}
.meta-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:8px;margin:16px 0;}
.meta-item{background:#f1f5f9;padding:10px 14px;border-radius:6px;}
.meta-label{font-size:11px;color:#64748b;} .meta-value{font-size:15px;font-weight:600;margin-top:2px;}
pre{background:#f8fafc;border:1px solid var(--border);border-radius:6px;padding:12px;font-size:12px;overflow-x:auto;max-height:300px;white-space:pre-wrap;word-break:break-all;}
@media print{body{padding:12px;} .chart-card{break-inside:avoid;}}
</style>");
        }

        private static void AppendHeader(StringBuilder sb, TestReportData d)
        {
            sb.AppendLine("<h1>测试报告</h1><div class='meta-grid'>");
            Meta(sb, "产品序列号", d.SN);
            Meta(sb, "工况", d.Condition);
            Meta(sb, "开始时间", d.StartTime.ToString("yyyy-MM-dd HH:mm:ss"));
            Meta(sb, "耗时", $"{(d.EndTime - d.StartTime).TotalSeconds:F1}s");
            Meta(sb, "执行策略", d.Strategy);
            Meta(sb, "执行ID", d.ExecutionId);
            sb.AppendLine("</div>");
        }

        private static void AppendOverallResult(StringBuilder sb, TestReportData d)
        {
            var css = d.OverallResult == "OK" ? "badge-ok" : "badge-ng";
            sb.AppendLine($"<h2>总体结果</h2><p><span class='{css}'>{E(d.OverallResult)}</span></p>");

            var ts = d.ScalarJudgments.Count;
            var ps = d.ScalarJudgments.Count(j => j.Pass);
            var tc = d.CurveJudgments.Count;
            var pc = d.CurveJudgments.Count(j => j.Pass);
            if (ts > 0 || tc > 0)
                sb.AppendLine($"<p>数值判定：{ps}/{ts} 通过 &nbsp;|&nbsp; 曲线判定：{pc}/{tc} 通过</p>");
        }

        private static void AppendScalarJudgmentTable(StringBuilder sb, List<ScalarJudgmentRow> rows)
        {
            sb.AppendLine("<h2>数值判定</h2><table>");
            sb.AppendLine("<tr><th>节点</th><th>参数</th><th>实际值</th><th>下限</th><th>上限</th><th>单位</th><th>判定</th></tr>");
            foreach (var r in rows)
            {
                var cls = r.Pass ? "pass" : "fail";
                sb.AppendLine($"<tr><td>{E(r.NodeName)}</td><td>{E(r.ParameterName)}</td>");
                sb.AppendLine($"<td>{Fmt(r.ActualValue)}</td><td>{Fmt(r.LowerLimit)}</td><td>{Fmt(r.UpperLimit)}</td>");
                sb.AppendLine($"<td>{E(r.Unit)}</td><td class='{cls}'>{(r.Pass ? "PASS" : "FAIL")}</td></tr>");
            }
            sb.AppendLine("</table>");
        }

        private static void AppendCurveJudgmentTable(StringBuilder sb, List<CurveJudgmentRow> rows)
        {
            sb.AppendLine("<h2>曲线判定</h2><table>");
            sb.AppendLine("<tr><th>节点</th><th>曲线</th><th>判定</th><th>失败详情</th></tr>");
            foreach (var r in rows)
            {
                var cls = r.Pass ? "pass" : "fail";
                sb.AppendLine($"<tr><td>{E(r.NodeName)}</td><td>{E(r.CurveName)}</td>");
                sb.AppendLine($"<td class='{cls}'>{(r.Pass ? "PASS" : "FAIL")}</td>");
                sb.AppendLine($"<td>{E(r.FailDetail ?? "-")}</td></tr>");
            }
            sb.AppendLine("</table>");

            foreach (var r in rows.Where(r => !string.IsNullOrEmpty(r.ChartImageBase64)))
            {
                sb.AppendLine($"<div class='chart-card'><div class='chart-title'>{E(r.CurveName)}</div>");
                sb.AppendLine($"<img src='data:image/png;base64,{r.ChartImageBase64}' /></div>");
            }
        }

        private static void AppendChartGallery(StringBuilder sb, List<ChartSection> charts)
        {
            sb.AppendLine("<h2>算法图表</h2><div>");
            foreach (var c in charts)
            {
                if (string.IsNullOrEmpty(c.ImageBase64)) continue;
                sb.AppendLine("<div class='chart-card'>");
                sb.AppendLine($"<div class='chart-title'>{E(c.Title)}</div>");
                sb.AppendLine($"<img src='data:image/png;base64,{c.ImageBase64}' width='{c.Width}' height='{c.Height}'/>");
                if (!string.IsNullOrEmpty(c.Description))
                    sb.AppendLine($"<div class='chart-desc'>{E(c.Description)}</div>");
                sb.AppendLine("</div>");
            }
            sb.AppendLine("</div>");
        }

        private static void AppendNodeSummaryTable(StringBuilder sb, List<NodeRunSummary> nodes)
        {
            sb.AppendLine("<h2>节点执行明细</h2><table>");
            sb.AppendLine("<tr><th>节点</th><th>状态</th><th>耗时</th><th>消息</th></tr>");
            foreach (var n in nodes)
            {
                sb.AppendLine($"<tr><td>{E(n.NodeName)}</td><td>{E(n.State)}</td>");
                sb.AppendLine($"<td>{n.Duration.TotalMilliseconds:F0}ms</td><td>{E(n.Message)}</td></tr>");
            }
            sb.AppendLine("</table>");
        }

        private static void AppendTextArtifacts(StringBuilder sb, List<TextArtifactSection> texts)
        {
            sb.AppendLine("<h2>附录：文本产物</h2>");
            foreach (var t in texts)
            {
                sb.AppendLine($"<h3>{E(t.Title)}</h3>");
                sb.AppendLine($"<pre>{E(t.Content)}</pre>");
            }
        }

        private static void Meta(StringBuilder sb, string label, string value)
        {
            sb.AppendLine($"<div class='meta-item'><div class='meta-label'>{E(label)}</div><div class='meta-value'>{E(value)}</div></div>");
        }

        private static string E(string? s) => WebUtility.HtmlEncode(s ?? "");
        private static string Fmt(double? v) => v.HasValue ? v.Value.ToString("F4") : "-";
    }
}
